# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding Notes
email: hey@thelucasmoore.com
description: > # this means to ignore newlines until "baseurl:"
  Hey. I'm Lucas Moore, a student at Learn.co Full-Stack Web Development Bootcamp.
  I write about Ruby on Rails, meditation and accelerated learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thelucasmoore.github.io" # the base hostname & protocol for your site
twitter_username: thelucasmoore
github_username:  thelucasmoore

# Build settings
markdown: kramdown
